# Use the official Node.js 16 image as the base image
FROM node:16 AS build
WORKDIR /app

RUN npm install -g @angular/cli
# Copy the package.json and package-lock.json files
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the entire project directory
COPY . .

# Build the application
RUN npm run build --prod

# Use a lightweight web server to serve the application
FROM nginx:alpine
COPY --from=build /app/dist/products-app-fe /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
